import type {Storyboard} from './schema';

export const exampleStoryboard: Storyboard = {
  version: 'visual-planner-v1',
  format: '9:16',
  width: 1080,
  height: 1920,
  fps: 30,
  title: 'How an AI agent uses the web',
  totalDurationSeconds: 30,
  narrationLanguage: 'en-US',
  shots: [
    {
      id: 'shot-01',
      startSeconds: 0,
      durationSeconds: 3.2,
      narration: 'An AI agent does not need to know everything before it starts.',
      purpose: 'hook',
      visualStrategy: 'demonstration',
      visualType: 'HYBRID',
      assets: [
        {
          id: 'agent-ui',
          type: 'UI_GENERATED',
          source: 'generated_ui',
          required: true,
          orientation: 'portrait',
          continuityKey: 'agent-interface',
        },
        {
          id: 'laptop',
          type: 'REAL_VIDEO',
          source: 'stock',
          required: true,
          orientation: 'portrait',
          minDurationSeconds: 3,
          query: 'person using laptop AI assistant',
          continuityKey: 'hero-device',
        },
      ],
      camera: {type: 'push_in', intensity: 0.2, focalPoint: {x: 0.55, y: 0.45}},
      motion: [
        {
          id: 'm01',
          trigger: 'question_received',
          target: 'agent-ui',
          action: 'appear',
          purpose: 'Establish the agent as the active subject.',
          startOffsetSeconds: 0.35,
          durationSeconds: 0.35,
        },
      ],
      typography: {
        enabled: true,
        text: 'It can look things up.',
        role: 'emphasis',
        maxWords: 5,
      },
      transition: {in: 'cut', out: 'match_cut'},
      continuity: {
        characters: [],
        locations: ['digital_workspace'],
        objects: ['hero-device', 'agent-interface'],
        styleKey: 'techpulse-dark-real-ui-v1',
        nextState: 'agent-receives-question',
      },
    },
    {
      id: 'shot-02',
      startSeconds: 3.2,
      durationSeconds: 4.0,
      narration: 'First, it turns the goal into a search task.',
      purpose: 'explain',
      visualStrategy: 'transformation',
      visualType: 'UI_GENERATED',
      assets: [
        {
          id: 'task-ui',
          type: 'UI_GENERATED',
          source: 'generated_ui',
          required: true,
          orientation: 'portrait',
          continuityKey: 'agent-interface',
        },
      ],
      camera: {type: 'macro_reveal', intensity: 0.25, focalPoint: {x: 0.5, y: 0.4}},
      motion: [
        {
          id: 'm02',
          trigger: 'goal_parsed',
          target: 'goal-text',
          action: 'transform',
          purpose: 'Show the goal becoming a concrete search task.',
          startOffsetSeconds: 0.45,
          durationSeconds: 0.7,
        },
        {
          id: 'm03',
          trigger: 'search_ready',
          target: 'search-bar',
          action: 'highlight',
          purpose: 'Direct attention to the next action.',
          startOffsetSeconds: 1.45,
          durationSeconds: 0.45,
        },
      ],
      typography: {enabled: false},
      transition: {in: 'match_cut', out: 'content_follow'},
      continuity: {
        characters: [],
        locations: ['digital_workspace'],
        objects: ['agent-interface'],
        styleKey: 'techpulse-dark-real-ui-v1',
        previousState: 'agent-receives-question',
        nextState: 'search-ready',
      },
    },
    {
      id: 'shot-03',
      startSeconds: 7.2,
      durationSeconds: 4.2,
      narration: 'Then it opens a browser and searches for evidence.',
      purpose: 'demonstrate',
      visualStrategy: 'demonstration',
      visualType: 'SCREEN_RECORDING',
      assets: [
        {
          id: 'browser',
          type: 'SCREEN_RECORDING',
          source: 'screenshot',
          required: true,
          orientation: 'portrait',
          minDurationSeconds: 4,
          query: 'browser search results technology research',
          continuityKey: 'research-browser',
        },
      ],
      camera: {type: 'follow', intensity: 0.16, focalPoint: {x: 0.5, y: 0.5}},
      motion: [
        {
          id: 'm04',
          trigger: 'browser_open',
          target: 'browser',
          action: 'appear',
          purpose: 'Show the tool being invoked.',
          startOffsetSeconds: 0.2,
          durationSeconds: 0.45,
        },
        {
          id: 'm05',
          trigger: 'search_submitted',
          target: 'results',
          action: 'reveal',
          purpose: 'Make the retrieval event visible.',
          startOffsetSeconds: 1.15,
          durationSeconds: 0.8,
        },
      ],
      typography: {enabled: false},
      transition: {in: 'content_follow', out: 'camera_move'},
      continuity: {
        characters: [],
        locations: ['web'],
        objects: ['research-browser'],
        styleKey: 'techpulse-dark-real-ui-v1',
        previousState: 'search-ready',
        nextState: 'results-visible',
      },
    },
    {
      id: 'shot-04',
      startSeconds: 11.4,
      durationSeconds: 4.6,
      narration: 'It does not just read the page. It selects the information that matters.',
      purpose: 'explain',
      visualStrategy: 'spatial_explanation',
      visualType: 'HYBRID',
      assets: [
        {
          id: 'page',
          type: 'REAL_IMAGE',
          source: 'screenshot',
          required: true,
          orientation: 'portrait',
          continuityKey: 'research-browser',
        },
        {
          id: 'selection-overlay',
          type: 'SVG',
          source: 'svg',
          required: true,
          orientation: 'portrait',
        },
      ],
      camera: {type: 'push_in', intensity: 0.28, focalPoint: {x: 0.5, y: 0.48}},
      motion: [
        {
          id: 'm06',
          trigger: 'relevance_detected',
          target: 'evidence-block',
          action: 'highlight',
          purpose: 'Show selection rather than merely showing a page.',
          startOffsetSeconds: 0.55,
          durationSeconds: 0.75,
        },
        {
          id: 'm07',
          trigger: 'evidence_selected',
          target: 'context-window',
          action: 'move',
          purpose: 'Show selected evidence entering the agent context.',
          startOffsetSeconds: 1.65,
          durationSeconds: 1.0,
        },
      ],
      typography: {enabled: true, text: 'RELEVANT EVIDENCE', role: 'label', maxWords: 2},
      transition: {in: 'camera_move', out: 'match_cut'},
      continuity: {
        characters: [],
        locations: ['web'],
        objects: ['research-browser', 'context-window'],
        styleKey: 'techpulse-dark-real-ui-v1',
        previousState: 'results-visible',
        nextState: 'evidence-in-context',
      },
    },
    {
      id: 'shot-05',
      startSeconds: 16.0,
      durationSeconds: 4.4,
      narration: 'Now the agent can use that evidence to improve its answer.',
      purpose: 'explain',
      visualStrategy: 'transformation',
      visualType: 'HYBRID',
      assets: [
        {
          id: 'context-window',
          type: 'UI_GENERATED',
          source: 'generated_ui',
          required: true,
          orientation: 'portrait',
          continuityKey: 'context-window',
        },
        {
          id: 'answer',
          type: 'UI_GENERATED',
          source: 'generated_ui',
          required: true,
          orientation: 'portrait',
        },
      ],
      camera: {type: 'pull_out', intensity: 0.2, focalPoint: {x: 0.5, y: 0.5}},
      motion: [
        {
          id: 'm08',
          trigger: 'context_complete',
          target: 'answer',
          action: 'replace',
          purpose: 'Make the improvement visible as a state change.',
          startOffsetSeconds: 0.65,
          durationSeconds: 0.9,
        },
      ],
      typography: {enabled: false},
      transition: {in: 'match_cut', out: 'content_follow'},
      continuity: {
        characters: [],
        locations: ['digital_workspace'],
        objects: ['context-window', 'answer'],
        styleKey: 'techpulse-dark-real-ui-v1',
        previousState: 'evidence-in-context',
        nextState: 'answer-improved',
      },
    },
    {
      id: 'shot-06',
      startSeconds: 20.4,
      durationSeconds: 4.4,
      narration: 'That is the difference between a model that only answers and an agent that can act.',
      purpose: 'compare',
      visualStrategy: 'comparison',
      visualType: 'HYBRID',
      assets: [
        {
          id: 'model-side',
          type: 'UI_GENERATED',
          source: 'generated_ui',
          required: true,
          orientation: 'portrait',
        },
        {
          id: 'agent-side',
          type: 'UI_GENERATED',
          source: 'generated_ui',
          required: true,
          orientation: 'portrait',
          continuityKey: 'agent-interface',
        },
      ],
      camera: {type: 'static', intensity: 0},
      motion: [
        {
          id: 'm09',
          trigger: 'comparison_start',
          target: 'agent-side',
          action: 'highlight',
          purpose: 'Make the tool-using behavior the visual focus.',
          startOffsetSeconds: 0.55,
          durationSeconds: 0.6,
        },
      ],
      typography: {enabled: true, text: 'ANSWER  vs  ACT', role: 'emphasis', maxWords: 4},
      transition: {in: 'cut', out: 'match_cut'},
      continuity: {
        characters: [],
        locations: ['comparison_space'],
        objects: ['model-side', 'agent-side'],
        styleKey: 'techpulse-dark-real-ui-v1',
        previousState: 'answer-improved',
        nextState: 'agent-acts',
      },
    },
    {
      id: 'shot-07',
      startSeconds: 24.8,
      durationSeconds: 3.8,
      narration: 'The tool is what closes the gap between knowledge and action.',
      purpose: 'payoff',
      visualStrategy: 'spatial_explanation',
      visualType: 'DIAGRAM',
      assets: [
        {
          id: 'knowledge-action-diagram',
          type: 'DIAGRAM',
          source: 'svg',
          required: true,
          orientation: 'portrait',
        },
      ],
      camera: {type: 'push_in', intensity: 0.22, focalPoint: {x: 0.5, y: 0.5}},
      motion: [
        {
          id: 'm10',
          trigger: 'tool_connection',
          target: 'knowledge-action-link',
          action: 'reveal',
          purpose: 'Show the conceptual bridge.',
          startOffsetSeconds: 0.4,
          durationSeconds: 0.8,
        },
      ],
      typography: {enabled: true, text: 'KNOWLEDGE → ACTION', role: 'emphasis', maxWords: 3},
      transition: {in: 'match_cut', out: 'fade'},
      continuity: {
        characters: [],
        locations: ['concept_space'],
        objects: ['knowledge-action-diagram'],
        styleKey: 'techpulse-dark-real-ui-v1',
        previousState: 'agent-acts',
        nextState: 'final-message',
      },
    },
    {
      id: 'shot-08',
      startSeconds: 28.6,
      durationSeconds: 1.4,
      narration: 'That is the core idea.',
      purpose: 'close',
      visualStrategy: 'hero_visual',
      visualType: 'HYBRID',
      assets: [
        {
          id: 'hero-lockup',
          type: 'SVG',
          source: 'svg',
          required: true,
          orientation: 'portrait',
        },
      ],
      camera: {type: 'static', intensity: 0},
      motion: [
        {
          id: 'm11',
          trigger: 'final_word',
          target: 'hero-lockup',
          action: 'scale',
          purpose: 'Provide a clean visual landing.',
          startOffsetSeconds: 0.1,
          durationSeconds: 0.5,
        },
      ],
      typography: {enabled: true, text: 'AI + TOOLS', role: 'title', maxWords: 2},
      transition: {in: 'fade', out: 'fade'},
      continuity: {
        characters: [],
        locations: ['concept_space'],
        objects: ['hero-lockup'],
        styleKey: 'techpulse-dark-real-ui-v1',
        previousState: 'final-message',
        nextState: 'end',
      },
    },
  ],
};
