export const generatedShots = [
  { id:"hook", query:"person using laptop technology work", caption:"Most AI videos explain the idea. They rarely show it.", type:"human-action", from:0, duration:78, trim:0, src:"media/typing.mp4", assetTitle:"fallback typing", sourcePage:"https://commons.wikimedia.org/wiki/Category:Typing", license:"Wikimedia Commons" },
  { id:"model", query:"video editing computer timeline editing", caption:"The fix is simple: edit in shots, not slides.", type:"process", from:78, duration:84, trim:0, src:"media/coffee.mp4", assetTitle:"fallback process", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" },
  { id:"narration", query:"person speaking microphone studio podcast", caption:"Start with the narration.", type:"human-action", from:162, duration:78, trim:0, src:"media/city.mp4", assetTitle:"fallback narration", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" },
  { id:"intent", query:"computer screen software interface programming", caption:"Then ask: what should the viewer actually see?", type:"screen", from:240, duration:84, trim:0, src:"media/typing.mp4", assetTitle:"fallback screen", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" },
  { id:"concrete", query:"close up computer keyboard hands technology", caption:"Not a circle. Not a card. A real visual.", type:"close-up", from:324, duration:78, trim:0, src:"media/coffee.mp4", assetTitle:"fallback closeup", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" },
  { id:"transition", query:"city street moving traffic technology", caption:"A change of place can carry a transition.", type:"environment", from:402, duration:90, trim:0, src:"media/city.mp4", assetTitle:"fallback environment", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" },
  { id:"detail", query:"server room computer hardware close up", caption:"A close-up can make the idea feel concrete.", type:"detail", from:492, duration:84, trim:0, src:"media/typing.mp4", assetTitle:"fallback detail", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" },
  { id:"rhythm", query:"camera operator filmmaking production", caption:"Then cut again before the image becomes wallpaper.", type:"production", from:576, duration:90, trim:0, src:"media/coffee.mp4", assetTitle:"fallback production", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" },
  { id:"graphic", query:"computer display data visualization screen", caption:"Graphics still matter. But they explain what footage cannot.", type:"screen", from:666, duration:102, trim:0, src:"media/city.mp4", assetTitle:"fallback graphics", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" },
  { id:"ending", query:"technology city night network computer", caption:"The timeline becomes a sequence of decisions.", type:"environment", from:768, duration:132, trim:0, src:"media/typing.mp4", assetTitle:"fallback ending", sourcePage:"https://commons.wikimedia.org/", license:"Wikimedia Commons" }
] as const;
